### ISSUE TITLE
Error in tests

### ISSUE THREAD

**Issue by tonyguo1987** [mikeseven/node-webgl#47]
I had some trouble in running examples in node-webgl. I installed node-webgl from here. node-glfw and freeimage are also installed successfully. I am using Windows 7/64bit and node.js4.2.6/64bit.

However if I run the applications in test/lesson02.js, I will receive the following error message.

```
C:\Program Files\nodejs\node_modules\node-webgl>node test\lesson02.js
C:\Program Files\nodejs\node_modules\node-webgl\node_modules\bindings\bindings.j
s:83
        throw e
        ^

Error: The specified module could not be found.
C:\Program Files\nodejs\node_modules\node-webgl\build\Release\webgl.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (C:\Program Files\nodejs\node_modules\node-webgl\node_modules\bi
ndings\bindings.js:76:44)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\node-webgl\lib\w
ebgl.js:1:108)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

C:\Program Files\nodejs\node_modules\node-webgl>
```
Very appreciated if you can give some suggestion of how I could fix it!

**Comment by mikeseven** [comment]
This happens typically when node doesn't find the native libraries.
Make sure node-glfw works by running its test. Do npm link ., to force it to be registered with node.

In node-webgl, do npm link node-glfw, to force linking it in case npm didn't install node-webgl correctly.

--mike



On Thu, Jan 28, 2016 at 1:43 AM -0800, "tonyguo1987" <notifications@github.com<mailto:notifications@github.com>> wrote:


I had some trouble in running examples in node-webgl I installed node-webgl from here node-glfw and freeimage are also installed successfully I am using Windows 7/64bit and nodejs426/64bit

However if I run the applications in test/lesson02js, I will receive the following error message

C:\Program Files\nodejs\node_modules\node-webgl>node test\lesson02js
C:\Program Files\nodejs\node_modules\node-webgl\node_modules\bindings\bindingsj
s:83
        throw e
        ^

Error: The specified module could not be found
C:\Program Files\nodejs\node_modules\node-webgl\build\Release\webglnode
    at Error (native)
    at Moduleload (modulejs:355:32)
    at FunctionModule_load (modulejs:310:12)
    at Modulerequire (modulejs:365:17)
    at require (modulejs:384:17)
    at bindings (C:\Program Files\nodejs\node_modules\node-webgl\node_modules\bi
ndings\bindingsjs:76:44)
    at Object<anonymous> (C:\Program Files\nodejs\node_modules\node-webgl\lib\w
ebgljs:1:108)
    at Module_compile (modulejs:434:26)
    at ObjectModule_extensionsjs (modulejs:452:10)
    at Moduleload (modulejs:355:32)

C:\Program Files\nodejs\node_modules\node-webgl>


Very appreciated if you can give some suggestion of how I could fix it!

-
