### ISSUE TITLE
three.js supports

### ISSUE THREAD

**Issue by dav-m85** [mikeseven/node-webgl#48]
For those interested, I just finished an example with three.js, looks like it is compatible. I haven't dug in more advanced examples yet.

https://github.com/mikeseven/node-webgl/compare/19a721e...dav-m85:master

**Comment by mikeseven** [comment]
Yes it is compatible. I haven't tested with the latest version though but I had no issue even with some complex demos and it runs way faster than in browsers.

--mike



On Tue, Mar 1, 2016 at 3:05 PM -0800, "dav-m85" <notifications@github.com<mailto:notifications@github.com>> wrote:


For those interested, I just finished an example with three.js, looks like it is compatible. I haven't dug in more advanced examples yet.

19a721e...dav-m85:master<https://github.com/mikeseven/node-webgl/compare/19a721e...dav-m85:master>

-

**Comment by mhirsch** [comment]
Thanks @dav-m85 

It would be really awesome to include this example in node-webgl. It seems to work out of the box with the version of threejs (r75 at the moment) that you can install using npm. The only issue is that that version doesn't have `#ifdef`s for highhp in the shaders.

**Comment by dav-m85** [comment]
I could open a pull request, but the example is pretty specific, so I'll let this to the good judgment of @mikeseven :) Happy to provide support if necessary.

**Comment by chexers** [comment]
I just removed the precision qualifier to try and get it working but I get an exception thrown by webgl.cc in  line 58. I  see there's a  block of  code commented  out. I  tried uncommenting  it but the method doesn't  exist  anymore.  Any ideas?

It happens when three.js tries to set a uniform3fv

**Comment by kid-wumeng** [comment]
@dav-m85 
I run your example and happen an error:

```
undefined
Status: Using GLEW 2.1.0
THREE.WebGLRenderer 90
THREE.WebGLRenderer: highp not supported, using lowp instead.
/Users/KID/Code/hello-c/node_modules/node-webgl/lib/webgl.js:483
    throw new TypeError('Expected getParameter(number pname)');
    ^

TypeError: Expected getParameter(number pname)
    at Object.getParameter (/Users/KID/Code/hello-c/node_modules/node-webgl/lib/webgl.js:483:11)
    at new WebGLCapabilities (/Users/KID/Code/hello-c/node_modules/three/build/three.js:19566:30)
    at initGLContext (/Users/KID/Code/hello-c/node_modules/three/build/three.js:21127:19)
    at new WebGLRenderer (/Users/KID/Code/hello-c/node_modules/three/build/three.js:21161:3)
    at init (/Users/KID/Code/hello-c/test.js:73:16)
    at webGLStart (/Users/KID/Code/hello-c/test.js:49:3)
    at Object.<anonymous> (/Users/KID/Code/hello-c/test.js:53:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

This is the message, I can't solve it... 
please tell me the reason and how to do = = ?

**Comment by mikeseven** [comment]
It seems I need to update for the latest version of threejs....

-- mike

________________________________
